### ISSUE TITLE
Install.sh error, script needs fixed

### ISSUE THREAD

**Issue by 0xebjc** [apogiatzis/gdb-peda-pwndbg-gef#3]
### Description: 
install.sh changes directories on line 51 ( line 51: cd ~/pwndbg ) but never changes back to the ~/gdb-peda-pwndbg-gef directory to run the subsequent cp commands between and throws multiple errors:

[+] Setting .gdbinit...
/home/user/pwndbg
cp: cannot stat './gdbinit': No such file or directory
[+] Creating files...
/home/user/pwndbg
cp: cannot stat './gdb-peda': No such file or directory
[-] Permission denied

### Steps to reproduce:
run the install.sh from ~/gdb-peda-pwndbg-gef

### Recommendation:
clean up install.sh and cd to the needed directory for each command

**Comment by IdanBanani** [comment]
Well, how can one fix it?

[+] Setting .gdbinit...
cp: cannot stat 'gdbinit': No such file or directory
[+] Creating files...
cp: cannot stat 'gdb-peda': No such file or directory
[-] Permission denied
-------------------------------------------------
seems like it works after installation for Ubuntu. 

But on Kali it won't work
kali@kali:~/gdb-peda-pwndbg-gef$ gdb-pwndbg
bash: gdb-pwndbg: command not found

kali@kali:~/gdb-peda-pwndbg-gef$ gdb-peda
bash: gdb-peda: command not found

**Comment by 0xebjc** [comment]
andrewbae fixed this issue and it was merged by apogiatzis, thanks for the fix!

https://github.com/apogiatzis/gdb-peda-pwndbg-gef/pull/6
